# Generated by Django 5.1.1 on 2025-10-23 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=2, verbose_name='U/M')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.CharField(max_length=150, verbose_name='Order #')),
                ('number_job', models.CharField(max_length=150, verbose_name='Job #')),
                ('assigned_date', models.DateField(verbose_name='Assigned')),
                ('crew', models.CharField(max_length=150, verbose_name='Crew')),
                ('crew_start_date', models.DateField(blank=True, null=True, verbose_name='Crew Start')),
                ('crew_end_date', models.DateField(blank=True, null=True, verbose_name='Crew End')),
                ('address', models.TextField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('products', models.ManyToManyField(through='workorder.ItemOrder', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='itemorder',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder'),
        ),
    ]
