version: "3.9"

services:
  web:
    build: .
    container_name: django_env
    command: >
      bash -c "\
      if [ ! -f manage.py ]; then \
        echo '📦 Creando nuevo proyecto Django...'; \
        django-admin startproject ace .; \
        echo '✅ Proyecto Django creado'; \
      fi; \
      echo '🚀 Iniciando servidor Django...'; \
      exec python manage.py runserver 0.0.0.0:8000 \
      "
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:15
    container_name: postgres_env_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
