# Generated by Django 5.1.1 on 2025-10-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(choices=[(True, 'Income'), (False, 'outflow')], default=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_finance', to='payment.paymentorder')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_finance', to='workorder.workorder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('work_order__isnull', False), ('payment__isnull', False), _connector='OR'), name='finance_must_have_entity')],
            },
        ),
    ]
