# Generated by Django 5.1.1 on 2025-10-23 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractor', '0001_initial'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=150, verbose_name='Job')),
                ('invoice', models.CharField(max_length=50, verbose_name='Invoice #')),
                ('assigned_date', models.DateField(verbose_name='Assigned')),
                ('crew_start_date', models.DateField(blank=True, null=True, verbose_name='Crew Start')),
                ('crew_end_date', models.DateField(blank=True, null=True, verbose_name='Crew End')),
                ('state', models.CharField(choices=[('in_progress', 'In progress'), ('done', 'Done'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor.contractor')),
                ('items_order', models.ManyToManyField(blank=True, related_name='payment_orders', to='workorder.itemorder')),
            ],
        ),
    ]
