# Generated by Django 5.1.1 on 2025-10-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('contact', models.CharField(max_length=150, verbose_name='Contact')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('other', models.TextField(verbose_name='Other')),
            ],
        ),
    ]
